# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/dma_sys/dma_sys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_sys || ORIG_REF_NAME==dma_sys} -quiet] -quiet

# IP: bd/dma_sys/ip/dma_sys_processing_system7_0_0/dma_sys_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_sys_processing_system7_0_0 || ORIG_REF_NAME==dma_sys_processing_system7_0_0} -quiet] -quiet

# IP: bd/dma_sys/ip/dma_sys_inverter_0_0/dma_sys_inverter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_sys_inverter_0_0 || ORIG_REF_NAME==dma_sys_inverter_0_0} -quiet] -quiet

# IP: bd/dma_sys/ip/dma_sys_axi_dma_0_0/dma_sys_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_sys_axi_dma_0_0 || ORIG_REF_NAME==dma_sys_axi_dma_0_0} -quiet] -quiet

# IP: bd/dma_sys/ip/dma_sys_ps7_0_axi_periph_0/dma_sys_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_sys_ps7_0_axi_periph_0 || ORIG_REF_NAME==dma_sys_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/dma_sys/ip/dma_sys_rst_ps7_0_50M_0/dma_sys_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_sys_rst_ps7_0_50M_0 || ORIG_REF_NAME==dma_sys_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/dma_sys/ip/dma_sys_xbar_0/dma_sys_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_sys_xbar_0 || ORIG_REF_NAME==dma_sys_xbar_0} -quiet] -quiet

# IP: bd/dma_sys/ip/dma_sys_axi_mem_intercon_0/dma_sys_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_sys_axi_mem_intercon_0 || ORIG_REF_NAME==dma_sys_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/dma_sys/ip/dma_sys_system_ila_0_0/dma_sys_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_sys_system_ila_0_0 || ORIG_REF_NAME==dma_sys_system_ila_0_0} -quiet] -quiet

# IP: bd/dma_sys/ip/dma_sys_auto_pc_0/dma_sys_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_sys_auto_pc_0 || ORIG_REF_NAME==dma_sys_auto_pc_0} -quiet] -quiet

# IP: bd/dma_sys/ip/dma_sys_auto_us_0/dma_sys_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_sys_auto_us_0 || ORIG_REF_NAME==dma_sys_auto_us_0} -quiet] -quiet

# IP: bd/dma_sys/ip/dma_sys_auto_us_1/dma_sys_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_sys_auto_us_1 || ORIG_REF_NAME==dma_sys_auto_us_1} -quiet] -quiet

# IP: bd/dma_sys/ip/dma_sys_auto_pc_1/dma_sys_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_sys_auto_pc_1 || ORIG_REF_NAME==dma_sys_auto_pc_1} -quiet] -quiet

# XDC: c:/ECE520/Lab8/dma_proj/dma_proj.gen/sources_1/bd/dma_sys/dma_sys_ooc.xdc
