# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ECE520/Lab8/dma_proj/dma_proj.srcs/sources_1/bd/dma_sys/ip/dma_sys_xbar_0/dma_sys_xbar_0.xci
# IP: The module: 'dma_sys_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE520/Lab8/dma_proj/dma_proj.gen/sources_1/bd/dma_sys/ip/dma_sys_xbar_0/dma_sys_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_sys_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/ECE520/Lab8/dma_proj/dma_proj.srcs/sources_1/bd/dma_sys/ip/dma_sys_xbar_0/dma_sys_xbar_0.xci
# IP: The module: 'dma_sys_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE520/Lab8/dma_proj/dma_proj.gen/sources_1/bd/dma_sys/ip/dma_sys_xbar_0/dma_sys_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_sys_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
