# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ECE520/Lab9/Part_2/lab/lab.srcs/sources_1/bd/Lab9_design_1/ip/Lab9_design_1_processing_system7_0_0/Lab9_design_1_processing_system7_0_0.xci
# IP: The module: 'Lab9_design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE520/Lab9/Part_2/lab/lab.gen/sources_1/bd/Lab9_design_1/ip/Lab9_design_1_processing_system7_0_0/Lab9_design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab9_design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/ECE520/Lab9/Part_2/lab/lab.srcs/sources_1/bd/Lab9_design_1/ip/Lab9_design_1_processing_system7_0_0/Lab9_design_1_processing_system7_0_0.xci
# IP: The module: 'Lab9_design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE520/Lab9/Part_2/lab/lab.gen/sources_1/bd/Lab9_design_1/ip/Lab9_design_1_processing_system7_0_0/Lab9_design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab9_design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
