# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Lab9_design_1/Lab9_design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab9_design_1 || ORIG_REF_NAME==Lab9_design_1} -quiet] -quiet

# IP: bd/Lab9_design_1/ip/Lab9_design_1_processing_system7_0_0/Lab9_design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab9_design_1_processing_system7_0_0 || ORIG_REF_NAME==Lab9_design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/Lab9_design_1/ip/Lab9_design_1_fir_top_0_0/Lab9_design_1_fir_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab9_design_1_fir_top_0_0 || ORIG_REF_NAME==Lab9_design_1_fir_top_0_0} -quiet] -quiet

# IP: bd/Lab9_design_1/ip/Lab9_design_1_fir_top_1_0/Lab9_design_1_fir_top_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab9_design_1_fir_top_1_0 || ORIG_REF_NAME==Lab9_design_1_fir_top_1_0} -quiet] -quiet

# IP: bd/Lab9_design_1/ip/Lab9_design_1_xbar_0/Lab9_design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab9_design_1_xbar_0 || ORIG_REF_NAME==Lab9_design_1_xbar_0} -quiet] -quiet

# IP: bd/Lab9_design_1/ip/Lab9_design_1_auto_pc_0/Lab9_design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab9_design_1_auto_pc_0 || ORIG_REF_NAME==Lab9_design_1_auto_pc_0} -quiet] -quiet

# IP: bd/Lab9_design_1/ip/Lab9_design_1_ps7_0_axi_periph_0/Lab9_design_1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab9_design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==Lab9_design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab9_design_1/ip/Lab9_design_1_rst_ps7_0_50M_0/Lab9_design_1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab9_design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==Lab9_design_1_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: c:/ECE520/Lab9/Part_2/lab/lab.gen/sources_1/bd/Lab9_design_1/Lab9_design_1_ooc.xdc
