# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zy10_const.xdc

# Block Designs: bd/Lab9_design_1/Lab9_design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab9_design_1 || ORIG_REF_NAME==Lab9_design_1} -quiet] -quiet

# IP: bd/Lab9_design_1/ip/Lab9_design_1_c_counter_binary_0_0/Lab9_design_1_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab9_design_1_c_counter_binary_0_0 || ORIG_REF_NAME==Lab9_design_1_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/Lab9_design_1/ip/Lab9_design_1_ila_0_0/Lab9_design_1_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab9_design_1_ila_0_0 || ORIG_REF_NAME==Lab9_design_1_ila_0_0} -quiet] -quiet

# IP: bd/Lab9_design_1/ip/Lab9_design_1_vio_0_0/Lab9_design_1_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab9_design_1_vio_0_0 || ORIG_REF_NAME==Lab9_design_1_vio_0_0} -quiet] -quiet

# IP: bd/Lab9_design_1/ip/Lab9_design_1_clk_wiz_1/Lab9_design_1_clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab9_design_1_clk_wiz_1 || ORIG_REF_NAME==Lab9_design_1_clk_wiz_1} -quiet] -quiet

# IP: bd/Lab9_design_1/ip/Lab9_design_1_xlslice_0_0/Lab9_design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab9_design_1_xlslice_0_0 || ORIG_REF_NAME==Lab9_design_1_xlslice_0_0} -quiet] -quiet

# XDC: c:/ECE520/Lab9/Lab_9_design/Lab_9_design.gen/sources_1/bd/Lab9_design_1/Lab9_design_1_ooc.xdc
