# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ECE520/Lab7/Part2/Custom_IP/Custom_IP/lab/KCU105/verilog/wave_gen.srcs/sources_1/ip/clk_core/clk_core.xci
# IP: The module: 'clk_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE520/Lab7/Part2/Custom_IP/Custom_IP/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/clk_core/clk_core_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/ECE520/Lab7/Part2/Custom_IP/Custom_IP/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/clk_core/clk_core.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/ECE520/Lab7/Part2/Custom_IP/Custom_IP/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/clk_core/clk_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/ECE520/Lab7/Part2/Custom_IP/Custom_IP/lab/KCU105/verilog/wave_gen.srcs/sources_1/ip/clk_core/clk_core.xci
# IP: The module: 'clk_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE520/Lab7/Part2/Custom_IP/Custom_IP/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/clk_core/clk_core_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/ECE520/Lab7/Part2/Custom_IP/Custom_IP/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/clk_core/clk_core.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/ECE520/Lab7/Part2/Custom_IP/Custom_IP/lab/KCU105/verilog/wave_gen.gen/sources_1/ip/clk_core/clk_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
